---
name: Publish wiki
permissions: {}

on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/workflows/publish-wiki.yml

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      - name: Publish wiki
        uses: Andrew-Chen-Wang/github-wiki-action@64efa0a9436db17670a2259e0ac249d6f08bb352  # v5.0.4
        with:
          path: docs/
